### ISSUE TITLE
Add the ability to specify extra locations for scan for Adapters

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#128]
This will make it much easier for end-users that have pip installed Grizzly to build and run custom adapters.

**Comment by jschwartzentruber** [comment]
We talked before about doing this in the same way as https://github.com/MozillaSecurity/grizzly/pull/46, using setuptools entrypoints. I thought there was an issue for this already, but I guess not.

**Comment by tysmith** [comment]
Yeah this should be handle by #210
