### ISSUE TITLE
[reducer] Local prefs file should not be deleted.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/grizzly#150]
STR:

* `prefpicker browser-fuzzing.yml prefs.js`
* `python -m grizzly.reduce firefox -p prefs.js empty.html`
* Ctrl+C to kill the reducer.

`prefs.js` will no longer be in the working directory. This happens in the Ctrl+C case and also if the testcase doesn't reproduce.

**Comment by tysmith** [comment]
Thanks, this should be fixed now.
