### ISSUE TITLE
testing the integration with FuzzManager

### ISSUE THREAD

**Issue by adrian-rt** [MozillaSecurity/grizzly#170]
Hi all,

So I just setup grizzly, I run FuzzManager as swell, is there a way  to test that if a bug is discovered it's actually working correctly and logging it to FuzzManager as well?

Thanks.

**Comment by tysmith** [comment]
Hi @adrian-rt,

In the browser address bar you can use `about:crashcontent` and `about:crashparent` to trigger crashes for testing. Note this can only be done by hand.

Happy fuzzing,
Tyson
