### ISSUE TITLE
Replace typo `grizzy` to `grizzly` in wiki

### ISSUE THREAD

**Issue by annygakh** [MozillaSecurity/grizzly#241]
This wiki page https://github.com/MozillaSecurity/grizzly/wiki/Grizzly-Replay has a typo in word `grizzly` as it is missing a letter l. There are two instances of such typos on the page. It doesn't seem like github supports pull requests for wikis, so I'm just filing an issue for this,

**Comment by tysmith** [comment]
Hey thanks! I've fixed the typo :)
