### ISSUE TITLE
RuntimeError: Failed to create FM signature

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/grizzly#71]
[2019-07-22 22:17:00] Starting Grizzly
[2019-07-22 22:17:00] Running with Xvfb
[2019-07-22 22:17:00] Found 0 input files(s)
[2019-07-22 22:17:00] Running in FUZZING mode
[2019-07-22 22:17:00] Using prefs '/home/firefox/code/browsers/prefs.js'
[2019-07-22 22:17:01] Results will be reported via FuzzManager
[2019-07-22 22:17:01] Launching target
[2019-07-22 22:17:05] I0001-R00 
[2019-07-22 22:17:36] I0002-R00 
[2019-07-22 22:18:42] I0004-R00 
[2019-07-22 22:21:16] Terminating browser...
[2019-07-22 22:21:16] Result detected
[2019-07-22 22:21:16] Reporting results...
[2019-07-22 22:21:16] Report is unsupported by FM, saved to '/tmp/grz_logs_h_wj9p'
[2019-07-22 22:21:16] Shutting down...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/firefox/code/grizzly/grizzly/__main__.py", line 13, in <module>
    sys.exit(console_main())
  File "grizzly/main.py", line 51, in console_main
    return main(GrizzlyArgs().parse_args())
  File "grizzly/main.py", line 161, in main
    session.run()
  File "grizzly/session.py", line 196, in run
    self.check_results(not files_served, server_status == sapphire.SERVED_TIMEOUT)
  File "grizzly/session.py", line 56, in check_results
    self.report_result()
  File "grizzly/session.py", line 155, in report_result
    self.reporter.submit(result_logs, self.iomanager.tests)
  File "grizzly/common/reporter.py", line 254, in submit
    self._submit(report, test_cases)
  File "grizzly/common/reporter.py", line 450, in _submit
    raise RuntimeError("Failed to create FM signature")
RuntimeError: Failed to create FM signature

This happens every few minutes

Here are the contents of /tmp/grz_logs_h_wj9p/:
at log_metadata.json 
{
  "log_stderr.txt": {
    "st_atime": 1563833821.0280266, 
    "st_blksize": 4096, 
    "st_blocks": 8, 
    "st_ctime": 1563834076.2376258, 
    "st_dev": 116, 
    "st_gid": 999, 
    "st_ino": 2097289, 
    "st_mode": 33152, 
    "st_mtime": 1563834076.2376258, 
    "st_nlink": 1, 
    "st_rdev": 0, 
    "st_size": 2137, 
    "st_uid": 999
  }, 
  "log_stdout.txt": {
    "st_atime": 1563833821.0280266, 
    "st_blksize": 4096, 
    "st_blocks": 8, 
    "st_ctime": 1563834015.2532432, 
    "st_dev": 116, 
    "st_gid": 999, 
    "st_ino": 2097288, 
    "st_mode": 33152, 
    "st_mtime": 1563834015.2532432, 
    "st_nlink": 1, 
    "st_rdev": 0, 
    "st_size": 1679, 
    "st_uid": 999
  }
}
[ffpuppet] Launch command: /home/firefox/code/browsers/firefox/firefox -no-remote -profile /tmp/ffprof_SPOzga http://127.0.0.1:32156

JavaScript error: resource://gre/modules/Sidebar.jsm, line 13: TypeError: window.docShell is null
JavaScript error: http://127.0.0.1:16023/test_0001.html, line 2677: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: http://127.0.0.1:16023/test_0002.html, line 4454: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: http://127.0.0.1:16023/test_0002.html, line 4454: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: , line 0: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: , line 0: NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
JavaScript error: http://127.0.0.1:16023/test_0002.html, line 3033: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: http://127.0.0.1:16023/test_0003.html, line 1580: SyntaxError: An invalid or illegal string was specified
JavaScript error: http://127.0.0.1:16023/test_0004.html, line 3619: SyntaxError: An invalid or illegal string was specified
JavaScript error: http://127.0.0.1:16023/test_0004.html, line 3619: SyntaxError: An invalid or illegal string was specified
JavaScript error: http://127.0.0.1:16023/test_0005.html, line 2951: SyntaxError: An invalid or illegal string was specified
JavaScript error: http://127.0.0.1:16023/test_0005.html, line 2951: SyntaxError: An invalid or illegal string was specified
JavaScript error: , line 0: AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.
JavaScript error: http://127.0.0.1:16023/test_0006.html, line 1388: TypeError: The expression cannot be converted to return the specified type.
JavaScript error: http://127.0.0.1:16023/test_0006.html, line 1601: TypeError: The expression cannot be converted to return the specified type.
[ffpuppet] Reason code: CLOSED

cat log_stdout.txt 
1563833822083	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1563833822083	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1563833822084	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1563833822084	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
[grz harness][Mon, 22 Jul 2019 22:17:05 GMT] Using test case time limit of 30000
1563833844682	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
[grz harness][Mon, 22 Jul 2019 22:17:35 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:17:35 GMT] Closing test case
[grz harness][Mon, 22 Jul 2019 22:18:08 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:18:08 GMT] Closing test case
[grz harness][Mon, 22 Jul 2019 22:18:41 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:18:41 GMT] Closing test case
[grz harness][Mon, 22 Jul 2019 22:19:12 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:19:12 GMT] Closing test case
[grz harness][Mon, 22 Jul 2019 22:19:44 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:19:44 GMT] Closing test case
[grz harness][Mon, 22 Jul 2019 22:20:15 GMT] Test case time limit exceeded
[grz harness][Mon, 22 Jul 2019 22:20:15 GMT] Closing test case

**Comment by tysmith** [comment]
Hey thanks for the report.

The issue here is a timeout:
> [grz harness][Mon, 22 Jul 2019 22:20:15 GMT] Test case time limit exceeded
> [grz harness][Mon, 22 Jul 2019 22:20:15 GMT] Closing test case

This will only happen when `--fuzzmanager` is used since there is no stack trace available to create a CrashInfo object. This is expected although not perfect. The workaround is to either ignore timeouts using `--ignore timeouts` or don't use `--fuzzmanager`. Note this will happen anytime a stack trace is not available to parse or if parsing a stack trace fails. Only the latter case is a real issue.

**Comment by kkuehl** [comment]
--ignore timeout works for me. Thanks!
