### ISSUE TITLE
[reducer] Remove file from test case as soon as it's no longer needed

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#99]
We currently remove all unnecessary files at the end of reduction, Doing this as soon as possible will be helpful when a reduction fails part way and the initial test case contains many files.

**Comment by pyoor** [comment]
Just to add to this, when reducing testcases with multiple files, any file not found to be served during the last successful iteration should be removed from the testcase.  This will help to improve reduction of intermittent testcases where allot of unnecessary time is spent reducing files known to not be required.

**Comment by tysmith** [comment]
Fixed by PR #168.
